import React from 'react';
import ReactDOM from 'react-dom';
// import App from './components/App.jsx';
// import TableMap from './components/TableMap.jsx';
// import State from './components/State.jsx';
// import Props1 from './components/Props1.jsx';
// import StateProps from './components/StateProps.jsx';
import Props2 from './components/Props2.jsx';
import SetState from './components/SetState.jsx';
import ForceUpdate from './components/ForceUpdate.jsx';
import FindDOMNode from './components/FindDOMNode.jsx';
import Form1 from './components/Form1.jsx';
import Form2Child from './components/Form2Child.jsx';
import Events from './components/Events.jsx';
import EventsChild from './components/EventsChild.jsx';

// ReactDOM.render(<App/>, document.getElementById("app"));
// ReactDOM.render(<TableMap />, document.getElementById('app'));
// ReactDOM.render(<State/>, document.getElementById('app'));
// ReactDOM.render(<Props1 headerProp="hoho header from props1" contentProp="haha content from props1"/>, document.getElementById('app'));
// ReactDOM.render(<Props1/>, document.getElementById('app'));
// ReactDOM.render(<StateProps/>, document.getElementById('app'));
// ReactDOM.render(<Props2/>, document.getElementById('app'));
// ReactDOM.render(<SetState/>, document.getElementById('app'));
// ReactDOM.render(<ForceUpdate/>, document.getElementById('app'));
// ReactDOM.render(<FindDOMNode/>, document.getElementById('app'));
// ReactDOM.render(<Form1/>, document.getElementById('app'));
// ReactDOM.render(<Form2Child/>, document.getElementById('app'));
// ReactDOM.render(<Events/>, document.getElementById('app'));
ReactDOM.render(<EventsChild/>, document.getElementById('app'));